'use client';
import {FormEvent,useEffect,useState} from 'react';import {createClient} from '@/lib/supabase-client';
export default function UsersManager(){
  const[rows,setRows]=useState<any[]>([]),[me,setMe]=useState(''),[open,setOpen]=useState(false),[loading,setLoading]=useState(false),[msg,setMsg]=useState('');
  const[nome,setNome]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[role,setRole]=useState('operador');
  async function load(){const s=createClient();const{data:{user}}=await s.auth.getUser();setMe(user?.id||'');const{data}=await s.from('profiles').select('id,nome,role,ativo,created_at').order('nome');setRows(data||[])}
  useEffect(()=>{load()},[]);
  async function patch(id:string,values:any){const{error}=await createClient().from('profiles').update(values).eq('id',id);if(error)alert(error.message);else load()}
  async function createUser(e:FormEvent){e.preventDefault();setLoading(true);setMsg('');const s=createClient();const{data:{session}}=await s.auth.getSession();if(!session){setMsg('Sessão expirada.');setLoading(false);return}const res=await fetch('/api/admin/users',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({nome,email,password,role})});const body=await res.json();setLoading(false);if(!res.ok){setMsg(body.error||'Não foi possível criar o usuário.');return}setMsg('Usuário criado com sucesso.');setNome('');setEmail('');setPassword('');setRole('operador');await load();setTimeout(()=>{setOpen(false);setMsg('')},900)}
  return <><div className="card tableCard"><div className="sectionHead usersHead"><div><b>Usuários cadastrados</b><small className="block">Gerencie acessos e níveis de permissão.</small></div><button className="btn" onClick={()=>setOpen(true)}>＋ Novo usuário</button></div><div className="tableWrap"><table className="table"><thead><tr><th>Nome</th><th>Perfil</th><th>Status</th><th>Cadastrado em</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.nome}</b>{r.id===me&&<small className="block">Você</small>}</td><td><select value={r.role} disabled={r.id===me} onChange={e=>patch(r.id,{role:e.target.value})}><option value="admin">Administrador</option><option value="tesouraria">Tesouraria</option><option value="operador">Operador</option></select></td><td><button disabled={r.id===me} className={'statusBtn '+(r.ativo?'active':'inactive')} onClick={()=>patch(r.id,{ativo:!r.ativo})}>{r.ativo?'Ativo':'Inativo'}</button></td><td>{new Date(r.created_at).toLocaleDateString('pt-BR')}</td></tr>)}</tbody></table></div></div>{open&&<div className="modalBackdrop" onMouseDown={()=>setOpen(false)}><form className="modalCard" onSubmit={createUser} onMouseDown={e=>e.stopPropagation()}><div className="modalTitle"><div><small>ADMINISTRAÇÃO</small><h2>Novo usuário</h2></div><button type="button" onClick={()=>setOpen(false)}>×</button></div><div className="field"><label>Nome</label><input value={nome} onChange={e=>setNome(e.target.value)} required/></div><div className="field"><label>E-mail</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></div><div className="field"><label>Senha inicial</label><input type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} required/><small className="block">Mínimo de 8 caracteres.</small></div><div className="field"><label>Nível de permissão</label><select value={role} onChange={e=>setRole(e.target.value)}><option value="operador">Operador — lançamentos e consultas</option><option value="tesouraria">Tesouraria — gestão financeira e auditoria</option><option value="admin">Administrador — acesso completo</option></select></div>{msg&&<div className={'notice '+(msg.includes('sucesso')?'ok':'err')}>{msg}</div>}<div className="modalActions"><button type="button" className="btn light" onClick={()=>setOpen(false)}>Cancelar</button><button disabled={loading} className="btn">{loading?'Criando...':'Criar usuário'}</button></div></form></div>}</>;
}
