'use client';
import {FormEvent,useEffect,useState} from 'react';import {createClient} from '@/lib/supabase-client';
export default function UsersManager(){
  const[rows,setRows]=useState<any[]>([]),[me,setMe]=useState(''),[open,setOpen]=useState(false),[loading,setLoading]=useState(false),[msg,setMsg]=useState('');
  const[nome,setNome]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[role,setRole]=useState('operador');
  const[resetUser,setResetUser]=useState<any|null>(null),[resetPass,setResetPass]=useState(''),[resetConfirm,setResetConfirm]=useState(''),[resetMsg,setResetMsg]=useState(''),[resetLoading,setResetLoading]=useState(false),[showReset,setShowReset]=useState(false);
  async function load(){const s=createClient();const{data:{user}}=await s.auth.getUser();setMe(user?.id||'');const{data}=await s.from('profiles').select('id,nome,role,ativo,created_at,must_change_password').order('nome');setRows(data||[])}
  useEffect(()=>{load()},[]);
  async function patch(id:string,values:any){const{error}=await createClient().from('profiles').update(values).eq('id',id);if(error)alert(error.message);else load()}
  async function createUser(e:FormEvent){e.preventDefault();setLoading(true);setMsg('');const s=createClient();const{data:{session}}=await s.auth.getSession();if(!session){setMsg('Sessão expirada.');setLoading(false);return}const res=await fetch('/api/admin/users',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({nome,email,password,role})});const body=await res.json();setLoading(false);if(!res.ok){setMsg(body.error||'Não foi possível criar o usuário.');return}setMsg('Usuário criado com sucesso.');setNome('');setEmail('');setPassword('');setRole('operador');await load();setTimeout(()=>{setOpen(false);setMsg('')},900)}
  async function resetPassword(e:FormEvent){e.preventDefault();setResetMsg('');if(resetPass.length<8){setResetMsg('A senha temporária deve ter pelo menos 8 caracteres.');return}if(resetPass!==resetConfirm){setResetMsg('As senhas não coincidem.');return}setResetLoading(true);const s=createClient();const{data:{session}}=await s.auth.getSession();if(!session){setResetLoading(false);setResetMsg('Sessão expirada.');return}const res=await fetch('/api/admin/users/reset-password',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({userId:resetUser.id,password:resetPass})});const body=await res.json();setResetLoading(false);if(!res.ok){setResetMsg(body.error||'Não foi possível redefinir a senha.');return}setResetMsg('Senha temporária criada. O usuário deverá trocá-la no próximo acesso.');await load();setTimeout(()=>{setResetUser(null);setResetPass('');setResetConfirm('');setResetMsg('');setShowReset(false)},1400)}
  return <><div className="card tableCard"><div className="sectionHead usersHead"><div><b>Usuários cadastrados</b><small className="block">Gerencie acessos, permissões e senhas temporárias.</small></div><button className="btn" onClick={()=>setOpen(true)}>＋ Novo usuário</button></div><div className="tableWrap"><table className="table"><thead><tr><th>Nome</th><th>Perfil</th><th>Status</th><th>Senha</th><th>Cadastrado em</th><th>Ações</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.nome}</b>{r.id===me&&<small className="block">Você</small>}</td><td><select value={r.role} disabled={r.id===me} onChange={e=>patch(r.id,{role:e.target.value})}><option value="admin">Administrador</option><option value="tesouraria">Tesouraria</option><option value="operador">Operador</option></select></td><td><button disabled={r.id===me} className={'statusBtn '+(r.ativo?'active':'inactive')} onClick={()=>patch(r.id,{ativo:!r.ativo})}>{r.ativo?'Ativo':'Inativo'}</button></td><td>{r.must_change_password?<span className="passwordPending">Troca pendente</span>:<span className="passwordOk">Definida</span>}</td><td>{new Date(r.created_at).toLocaleDateString('pt-BR')}</td><td>{r.id!==me?<button className="btn light resetPasswordBtn" onClick={()=>{setResetUser(r);setResetPass('');setResetConfirm('');setResetMsg('')}}>🔒 Redefinir senha</button>:<span>—</span>}</td></tr>)}</tbody></table></div></div>
  {open&&<div className="modalBackdrop" onMouseDown={()=>setOpen(false)}><form className="modalCard" onSubmit={createUser} onMouseDown={e=>e.stopPropagation()}><div className="modalTitle"><div><small>ADMINISTRAÇÃO</small><h2>Novo usuário</h2></div><button type="button" onClick={()=>setOpen(false)}>×</button></div><div className="field"><label>Nome</label><input value={nome} onChange={e=>setNome(e.target.value)} required/></div><div className="field"><label>E-mail</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></div><div className="field"><label>Senha inicial</label><input type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} required/><small className="block">Mínimo de 8 caracteres.</small></div><div className="field"><label>Nível de permissão</label><select value={role} onChange={e=>setRole(e.target.value)}><option value="operador">Operador — lançamentos e consultas</option><option value="tesouraria">Tesouraria — gestão financeira e auditoria</option><option value="admin">Administrador — acesso completo</option></select></div>{msg&&<div className={'notice '+(msg.includes('sucesso')?'ok':'err')}>{msg}</div>}<div className="modalActions"><button type="button" className="btn light" onClick={()=>setOpen(false)}>Cancelar</button><button disabled={loading} className="btn">{loading?'Criando...':'Criar usuário'}</button></div></form></div>}
  {resetUser&&<div className="modalBackdrop" onMouseDown={()=>setResetUser(null)}><form className="modalCard passwordResetAdmin" onSubmit={resetPassword} onMouseDown={e=>e.stopPropagation()}><div className="modalTitle"><div><small>SEGURANÇA</small><h2>Redefinir senha</h2></div><button type="button" onClick={()=>setResetUser(null)}>×</button></div><div className="resetUserName"><b>{resetUser.nome}</b><small>O usuário será obrigado a criar uma senha pessoal no próximo acesso.</small></div><div className="field"><label>Nova senha temporária</label><div className="passwordField"><input type={showReset?'text':'password'} minLength={8} value={resetPass} onChange={e=>setResetPass(e.target.value)} required/><button type="button" onClick={()=>setShowReset(v=>!v)}>{showReset?'Ocultar':'Mostrar'}</button></div><small className="block">Mínimo de 8 caracteres.</small></div><div className="field"><label>Confirmar senha temporária</label><input type={showReset?'text':'password'} minLength={8} value={resetConfirm} onChange={e=>setResetConfirm(e.target.value)} required/></div>{resetMsg&&<div className={'notice '+(resetMsg.includes('criada')?'ok':'err')}>{resetMsg}</div>}<div className="modalActions"><button type="button" className="btn light" onClick={()=>setResetUser(null)}>Cancelar</button><button disabled={resetLoading} className="btn">{resetLoading?'Redefinindo...':'Redefinir senha'}</button></div></form></div>}</>;
}
